$ErrorActionPreference = "Stop"

. (Join-Path $PSScriptRoot 'lib\agent-library.ps1')

$workspaceRoot = Split-Path $PSScriptRoot -Parent
$catalogDir = Join-Path $workspaceRoot '.agent\catalog'

if (-not (Test-Path -LiteralPath $catalogDir)) {
  New-Item -ItemType Directory -Path $catalogDir | Out-Null
}

$registryRecords = Get-RoleRegistryRecords -WorkspaceRoot $workspaceRoot
$roleFiles = Get-AgentRoleFiles -WorkspaceRoot $workspaceRoot
$commandFiles = Get-AgentCommandFiles -WorkspaceRoot $workspaceRoot

$roleRows = foreach ($record in $registryRecords) {
  $fullPath = Join-Path $workspaceRoot $record.source
  $frontmatter = if (Test-Path -LiteralPath $fullPath) { Get-AgentLibraryFrontmatter -Path $fullPath } else { $null }
  [pscustomobject]@{
    name = $record.name
    kind = $record.kind
    route_status = $record.route_status
    review_gate = $record.review_gate
    type = if ($frontmatter -and $frontmatter.PSObject.Properties.Name -contains 'type') { $frontmatter.type } else { 'unspecified' }
    summary = if ($frontmatter -and $frontmatter.PSObject.Properties.Name -contains 'description') {
      (($frontmatter.description -split "\r?\n")[0]).Trim()
    } else {
      $record.responsibility
    }
    source = $record.source
  }
}

$commandRows = foreach ($file in $commandFiles) {
  $frontmatter = Get-AgentLibraryFrontmatter -Path $file.FullName
  [pscustomobject]@{
    name = $frontmatter.name
    description = if ($frontmatter.description) { (($frontmatter.description -split "\r?\n")[0]).Trim() } else { '' }
    uses = if ($frontmatter.uses -is [System.Array]) { ($frontmatter.uses -join ', ') } else { [string]$frontmatter.uses }
    outputs = if ($frontmatter.outputs -is [System.Array]) { ($frontmatter.outputs -join ', ') } else { [string]$frontmatter.outputs }
    review_gate = [string]$frontmatter.review_gate
    estimated_time = [string]$frontmatter.'estimated_time'
    source = Get-RelativeWorkspacePath -Path $file.FullName -WorkspaceRoot $workspaceRoot
  }
}

$rolesMd = [System.Collections.Generic.List[string]]::new()
$rolesMd.Add('# Roles By Route Status') | Out-Null
$rolesMd.Add('') | Out-Null
$rolesMd.Add('_Generated by `scripts/build-agent-catalog.ps1`._') | Out-Null
$rolesMd.Add('') | Out-Null

foreach ($status in @('core', 'conditional', 'support', 'governance')) {
  $rolesMd.Add("## $status") | Out-Null
  $rolesMd.Add('') | Out-Null
  $rolesMd.Add('| Name | Kind | Execution Style | Review Gate | Summary | Source |') | Out-Null
  $rolesMd.Add('|---|---|---|---|---|---|') | Out-Null

  foreach ($row in $roleRows | Where-Object { $_.route_status -eq $status } | Sort-Object kind, name) {
    $sourceCell = [string]::Concat('`', $row.source, '`')
    $rolesMd.Add("| $($row.name) | $($row.kind) | $($row.type) | $($row.review_gate) | $($row.summary) | $sourceCell |") | Out-Null
  }

  $rolesMd.Add('') | Out-Null
}

Set-Content -LiteralPath (Join-Path $catalogDir 'roles-by-route-status.md') -Value $rolesMd -Encoding UTF8

$commandsMd = [System.Collections.Generic.List[string]]::new()
$commandsMd.Add('# Commands Catalog') | Out-Null
$commandsMd.Add('') | Out-Null
$commandsMd.Add('_Generated by `scripts/build-agent-catalog.ps1`._') | Out-Null
$commandsMd.Add('') | Out-Null
$commandsMd.Add('| Command | Uses | Outputs | Review Gate | ETA | Source |') | Out-Null
$commandsMd.Add('|---|---|---|---|---|---|') | Out-Null

foreach ($row in $commandRows | Sort-Object name) {
  $sourceCell = [string]::Concat('`', $row.source, '`')
  $commandsMd.Add("| $($row.name) | $($row.uses) | $($row.outputs) | $($row.review_gate) | $($row.estimated_time) | $sourceCell |") | Out-Null
}

$commandsMd.Add('') | Out-Null
Set-Content -LiteralPath (Join-Path $catalogDir 'commands.md') -Value $commandsMd -Encoding UTF8

$yaml = [System.Collections.Generic.List[string]]::new()
$yaml.Add("generated_at: $(Get-Date -Format 'yyyy-MM-ddTHH:mm:ssK')") | Out-Null
$yaml.Add('roles:') | Out-Null
foreach ($status in @('core', 'conditional', 'support', 'governance')) {
  $yaml.Add("  ${status}:") | Out-Null
  $items = $roleRows | Where-Object { $_.route_status -eq $status } | Sort-Object name
  if ($items.Count -eq 0) {
    $yaml.Add('    []') | Out-Null
    continue
  }

  foreach ($item in $items) {
    $yaml.Add("    - name: $($item.name)") | Out-Null
    $yaml.Add("      kind: $($item.kind)") | Out-Null
    $yaml.Add("      execution_style: $($item.type)") | Out-Null
    $yaml.Add("      review_gate: ""$($item.review_gate)""") | Out-Null
    $yaml.Add("      source: ""$($item.source)""") | Out-Null
  }
}

$yaml.Add('commands:') | Out-Null
foreach ($command in $commandRows | Sort-Object name) {
  $yaml.Add("  - name: $($command.name)") | Out-Null
  $yaml.Add("    review_gate: ""$($command.review_gate)""") | Out-Null
  $yaml.Add("    estimated_time: ""$($command.estimated_time)""") | Out-Null
  $yaml.Add('    uses:') | Out-Null
  foreach ($use in ($command.uses -split ', ' | Where-Object { $_ })) {
    $yaml.Add("      - $use") | Out-Null
  }
  $yaml.Add("    source: ""$($command.source)""") | Out-Null
}

Set-Content -LiteralPath (Join-Path $catalogDir 'routing-map.yaml') -Value $yaml -Encoding UTF8

Write-Output "CATALOG:PASS"
Write-Output "- Roles indexed: $($roleRows.Count)"
Write-Output "- Commands indexed: $($commandRows.Count)"
Write-Output "- Output dir: .agent/catalog"
